require("maliek.core.options")
require("maliek.core.keymaps")
require("maliek.core.colorscheme")
local cppfuncs = require("maliek.core.cppfunctions")
require("maliek.plugins.harpoon")
require("maliek.plugins.lsp")
require("maliek.plugins.lint")
require("maliek.plugins.telescope")
require("maliek.plugins.treesitter")

vim.api.nvim_create_user_command('CppCompilef', cppfuncs.CompileFile, {})
vim.api.nvim_create_user_command('CppCompile', cppfuncs.Compile, {})
